### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: A lock was created but not released

### ISSUE THREAD

**Issue by mnods** [LafColITS/moodle-tool_deletecourses#14]
Hi, getting this on mdl 3.9.3

Adhoc task failed: tool_deletecourses\task\delete_courses_task,Coding error detected, it must be fixed by a programmer: A lock was created but not released at:
admin/tool/deletecourses/classes/task/delete_courses_task.php on line 108

 Code should look like:

 $factory = \core\lock\lock_config::get_lock_factory('type');
 $lock = $factory->get_lock(211324237);
 $lock->release();  // Locks must ALWAYS be released like this.

Backtrace:
* line 113 of /admin/tool/deletecourses/classes/task/delete_courses_task.php: call to core\lock\lock->__destruct()
* line 75 of /admin/tool/deletecourses/classes/task/delete_courses_task.php: call to tool_deletecourses\task\delete_courses_task->delete_courses_in_category()
* line 333 of /lib/cronlib.php: call to tool_deletecourses\task\delete_courses_task->execute()
* line 198 of /lib/cronlib.php: call to cron_run_inner_adhoc_task()
* line 76 of /lib/cronlib.php: call to cron_run_adhoc_tasks()
* line 79 of /admin/cli/cron.php: call to cron_run()

**Comment by mackensen** [comment]
This typically means that there was a fatal error during execution, and not necessarily related to the plugin itself. Does this keep happening, and is there any other debugging information generated?

**Comment by mnods** [comment]
yes, sorry, ignore me, thought it was highlighting a change of code needed for unlocking but i see it looks right now i check. On a test environment i've been fiddling with so really no surprise it failed. will run through again but i'm sure it's actually ok. cheers for reply and code, much appreciated.
